version: '3'
services:
  postgres:
    container_name: personality_db
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=personalities
    ports:
      - "5432:5432"
    volumes:
      - ./migration/database-initial.sql:/docker-entrypoint-initdb.d/database-initial.sql
